version: '3.1'

services:

  mongo:
    image: mongo
    container_name: mongo_local
    restart: always
    ports:
      - 27017:27017
    command: --noauth
    volumes:
      - mongo-data:/db/data:ro
volumes:
  mongo-data: